server:
  port: 8888

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          default-label: origin
          uri: https://github.com/EngAhmedSalah/ConfigServerRepo.git
          clone-on-start: true
          search-paths: /config
          timeout: 5  # Set a 5-second timeout

encrypt:
  key: mykey

#        vault:
#          host: localhost
#          port: 8200
#          scheme: http
#          authentication: token
#          token: root
#          backend: secret
#          default-context: application
